name: ML-Training-Pipeline
on: [push]

permissions:
  contents: write # Permiso para que la Action suba el modelo

jobs:
  entrenar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar Librerias
        run: pip install pandas scikit-learn joblib

      - name: Ejecutar Entrenamiento
        run: python src/train.py

      - name: Subir el modelo al repositorio
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 1. # AÑADIR LOS DOS ARCHIVOS AQUÍ:
          git add models/soccer_model.pkl models/team_stats.csv
          
          # 2. Hacemos el commit ANTES del pull (esto quita el error de 'unstaged changes')
          git commit -m "Actualización automática del modelo [skip ci]" || echo "Sin cambios"
          
          # 3. Ahora sí, nos ponemos al día con lo que haya en GitHub
          git pull --rebase origin main
          
          # 4. Empujamos el resultado final
          git push origin main
