name: ML-Training-Pipeline
on: [push]

permissions:
  contents: write # Permiso para que la Action suba el modelo

jobs:
  entrenar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar Librerias
        run: pip install pandas scikit-learn joblib

      - name: Ejecutar Entrenamiento
        run: python src/train.py

      - name: Subir el modelo al repositorio
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 1. Traer los cambios más recientes para evitar el error de 'rejected'
          git pull origin main --rebase
          
          # 2. Añadir el modelo
          git add models/soccer_model.pkl
          
          # 3. Hacer el commit (solo si hay cambios)
          git commit -m "Actualización automática del modelo [skip ci]" || echo "Sin cambios para subir"
          
          # 4. Empujar los cambios
          git push origin main
